CREATE DATABASE PRUEBA_C;
go

USE PRUEBA_C;
go

CREATE TABLE ROLES(
ID BIGINT NOT NULL PRIMARY KEY IDENTITY,
NOM_ROL VARCHAR(25) NOT NULL
);
GO

CREATE PROCEDURE CONSULTAR_ROL_POR_ID
@ID BIGINT
AS 
SELECT * FROM ROLES WHERE ID = @ID;
GO

CREATE PROCEDURE CONSULTAR_ROL_POR_NOMBRE
@NOMBRE VARCHAR(25)
AS 
SELECT * FROM ROLES WHERE NOM_ROL = @NOMBRE;
GO

CREATE PROCEDURE CONSULTAR_ROLES
AS 
SELECT * FROM ROLES;
GO

---INSERTANDO VALORES DE ROLES.
INSERT INTO ROLES(NOM_ROL) VALUES('admin'),('usuario');
GO

CREATE TABLE ESTADOS(
ID BIGINT NOT NULL PRIMARY KEY IDENTITY,
NOM_ESTADO VARCHAR(25) NOT NULL
);
GO

CREATE PROCEDURE CONSULTAR_ESTADO_POR_ID
@ID BIGINT
AS 
SELECT * FROM ESTADOS WHERE ID = @ID;
GO


CREATE PROCEDURE CONSULTAR_ESTADO_POR_NOMBRE
@NOMBRE VARCHAR(25)
AS 
SELECT * FROM ESTADOS WHERE NOM_ESTADO = @NOMBRE;
GO

---INSERTANDO VALORES DE ROLES.
INSERT INTO ESTADOS(NOM_ESTADO) VALUES('abierto'),('cerrado');
GO

CREATE TABLE USUARIOS(
ID BIGINT NOT NULL PRIMARY KEY IDENTITY,
USUARIO VARCHAR(150) NOT NULL,
CLAVE VARCHAR(250) NOT NULL,
ID_ROL BIGINT NOT NULL REFERENCES ROLES(ID),
FECHA_CREACION DATETIME NOT NULL
);
GO
--SP

--PROCEDIMIENTO ALMACENADO AGREGAR_USUARIOS--
CREATE PROCEDURE AGREGAR_USUARIOS
@USUARIO VARCHAR(150),@CLAVE VARCHAR(250),@ID_ROL BIGINT,@FECHA_CREACION DATETIME
AS 
INSERT INTO USUARIOS(USUARIO,CLAVE,ID_ROL,FECHA_CREACION)
VALUES(@USUARIO,HashBytes('MD5',@CLAVE),@ID_ROL,@FECHA_CREACION);
GO


CREATE PROCEDURE VALIDAR_LOGIN
@USUARIO VARCHAR(150),
@CLAVE VARCHAR(250)
AS 
SELECT * FROM USUARIOS WHERE USUARIO = @USUARIO AND CLAVE = HashBytes('MD5',@CLAVE);
GO


--PROCEDIMIENTO ALMACENADO CONSULTAR_USUARIOS--
CREATE PROCEDURE CONSULTAR_USUARIOS
AS 
SELECT ID,USUARIO,CLAVE,ID_ROL,FECHA_CREACION FROM USUARIOS;
GO

--PROCEDIMIENTO ALMACENADO MODIFICARUSUARIOS--
CREATE PROCEDURE MODIFICAR_USUARIOS
@ID BIGINT,@USUARIO VARCHAR(150),@CLAVE VARCHAR(250),@ID_ROL BIGINT,@FECHA_CREACION DATETIME
AS
UPDATE USUARIOS SET USUARIO = @USUARIO,CLAVE = @CLAVE,ID_ROL = @ID_ROL,FECHA_CREACION = @FECHA_CREACION
WHERE ID = @ID;
GO

--PROCEDIMIENTO ALMACENADO ELIMINAR_USUARIOS--
CREATE PROCEDURE ELIMINAR_USUARIOS
@ID BIGINT
AS
DELETE FROM USUARIOS WHERE ID = @ID;
GO

--PROCEDIMIENTO ALMACENADO CONSULTAR_USUARIOS_POR_ID--
CREATE PROCEDURE CONSULTAR_USUARIOS_POR_ID
@ID BIGINT
AS
SELECT * FROM USUARIOS WHERE ID = @ID;
GO
----------------------------------------------------------------------


CREATE TABLE PREGUNTAS(
ID BIGINT NOT NULL PRIMARY KEY IDENTITY,
PREGUNTA VARCHAR(250) NOT NULL,
FECHA_CREACION DATETIME NOT NULL,
ID_ESTADO BIGINT NOT NULL REFERENCES ESTADOS(ID),
ID_USUARIO BIGINT NOT NULL REFERENCES USUARIOS(ID)
);
GO
--SP

--PROCEDIMIENTO ALMACENADO AGREGAR_PREGUNTAS--
CREATE PROCEDURE AGREGAR_PREGUNTAS
@PREGUNTA VARCHAR(250),@FECHA_CREACION DATETIME,@ID_ESTADO BIGINT,@ID_USUARIO BIGINT
AS 
INSERT INTO PREGUNTAS(PREGUNTA,FECHA_CREACION,ID_ESTADO,ID_USUARIO)
VALUES(@PREGUNTA,@FECHA_CREACION,@ID_ESTADO,@ID_USUARIO);
GO

CREATE PROCEDURE CAMBIAR_ESTADO_PREGUNTA
@ID_ESTADO BIGINT,
@ID_PREGUNTA BIGINT
AS 
UPDATE PREGUNTAS SET ID_ESTADO = @ID_ESTADO WHERE ID = @ID_PREGUNTA;
GO

--PROCEDIMIENTO ALMACENADO CONSULTAR_PREGUNTAS--
CREATE PROCEDURE CONSULTAR_PREGUNTAS
AS 
SELECT ID,PREGUNTA,FECHA_CREACION,ID_ESTADO,ID_USUARIO FROM PREGUNTAS ORDER BY FECHA_CREACION DESC;
GO

--PROCEDIMIENTO ALMACENADO MODIFICARPREGUNTAS--
CREATE PROCEDURE MODIFICAR_PREGUNTAS
@ID BIGINT,@PREGUNTA VARCHAR(250),@FECHA_CREACION DATETIME,@ID_ESTADO BIGINT,@ID_USUARIO BIGINT
AS
UPDATE PREGUNTAS SET PREGUNTA = @PREGUNTA,FECHA_CREACION = @FECHA_CREACION,ID_ESTADO = @ID_ESTADO,ID_USUARIO = @ID_USUARIO
WHERE ID = @ID;
GO

--PROCEDIMIENTO ALMACENADO ELIMINAR_PREGUNTAS--
CREATE PROCEDURE ELIMINAR_PREGUNTAS
@ID BIGINT
AS
DELETE FROM PREGUNTAS WHERE ID = @ID;
GO

--PROCEDIMIENTO ALMACENADO CONSULTAR_PREGUNTAS_POR_ID--
CREATE PROCEDURE CONSULTAR_PREGUNTAS_POR_ID
@ID BIGINT
AS
SELECT * FROM PREGUNTAS WHERE ID = @ID;
GO

---------------------------------------------------

CREATE TABLE RESPUESTAS(
ID BIGINT NOT NULL PRIMARY KEY IDENTITY,
RESPUESTA VARCHAR(250) NOT NULL,
FECHA_CREACION DATETIME NOT NULL,
ID_USUARIO BIGINT NOT NULL REFERENCES USUARIOS(ID),
ID_PREGUNTA BIGINT NOT NULL REFERENCES PREGUNTAS(ID)
);
go

--PROCEDIMIENTO ALMACENADO AGREGAR_RESPUESTAS--
CREATE PROCEDURE AGREGAR_RESPUESTAS
@RESPUESTA VARCHAR(250),@FECHA_CREACION DATETIME,@ID_USUARIO BIGINT,@ID_PREGUNTA BIGINT
AS 
INSERT INTO RESPUESTAS(RESPUESTA,FECHA_CREACION,ID_USUARIO,ID_PREGUNTA)
VALUES(@RESPUESTA,@FECHA_CREACION,@ID_USUARIO,@ID_PREGUNTA);
GO

--PROCEDIMIENTO ALMACENADO CONSULTAR_RESPUESTAS--
CREATE PROCEDURE CONSULTAR_RESPUESTAS
AS 
SELECT ID,RESPUESTA,FECHA_CREACION,ID_USUARIO,ID_PREGUNTA FROM RESPUESTAS;
GO

--PROCEDIMIENTO ALMACENADO MODIFICARRESPUESTAS--
CREATE PROCEDURE MODIFICAR_RESPUESTAS
@ID BIGINT,@RESPUESTA VARCHAR(250),@FECHA_CREACION DATETIME,@ID_USUARIO BIGINT,@ID_PREGUNTA BIGINT
AS
UPDATE RESPUESTAS SET RESPUESTA = @RESPUESTA,FECHA_CREACION = @FECHA_CREACION,ID_USUARIO = @ID_USUARIO,ID_PREGUNTA = @ID_PREGUNTA
WHERE ID = @ID;
GO

--PROCEDIMIENTO ALMACENADO ELIMINAR_RESPUESTAS--
CREATE PROCEDURE ELIMINAR_RESPUESTAS
@ID BIGINT
AS
DELETE FROM RESPUESTAS WHERE ID = @ID;
GO

--PROCEDIMIENTO ALMACENADO CONSULTAR_RESPUESTAS_POR_ID--
CREATE PROCEDURE CONSULTAR_RESPUESTAS_POR_ID
@ID BIGINT
AS
SELECT * FROM RESPUESTAS WHERE ID = @ID;
GO

--PROCEDIMIENTO ALMACENADO CONSULTAR_RESPUESTAS_POR_ID_PREGUNTA--
CREATE PROCEDURE CONSULTAR_RESPUESTAS_POR_ID_PREGUNTA
@ID_PREGUNTA BIGINT
AS
SELECT * FROM RESPUESTAS WHERE ID_PREGUNTA = @ID_PREGUNTA;
GO








